apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: {{ .Values.app.namespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-alb-ingress
  namespace: {{ .Values.app.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.app.name }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: {{ .Values.app.port }}
          protocol: TCP
      from:
        - ipBlock:
            cidr: {{ .Values.networkPolicy.vpcCidr }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress
  namespace: {{ .Values.app.namespace }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress
  namespace: {{ .Values.app.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.app.name }}
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 3306
          protocol: TCP
      to:
        - ipBlock:
            cidr: {{ .Values.networkPolicy.vpcCidr }}
    - ports:
        - port: 443
          protocol: TCP
      to:
        - ipBlock:
            cidr: "0.0.0.0/0"
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-worker-egress
  namespace: {{ .Values.app.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.worker.name }}
  policyTypes:
    - Egress
  egress:
    - ports:
        - port: 443
          protocol: TCP
      to:
        - ipBlock:
            cidr: "0.0.0.0/0"
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
