apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.app.secretProviderClassName }}
  namespace: {{ .Values.app.namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "kunlatek/app"
        objectType: "secretsmanager"
        jmesPath:
          - path: DATABASE_URL
            objectAlias: DATABASE_URL
          - path: JWT_SECRET
            objectAlias: JWT_SECRET
          - path: GCS_PROJECT_ID
            objectAlias: GCS_PROJECT_ID
          - path: GCS_PUBLIC_BUCKET_NAME
            objectAlias: GCS_PUBLIC_BUCKET_NAME
          - path: GCS_PRIVATE_BUCKET_NAME
            objectAlias: GCS_PRIVATE_BUCKET_NAME
          - path: GCS_CREDENTIALS
            objectAlias: GCS_CREDENTIALS
          - path: DATADOG_API_KEY
            objectAlias: DATADOG_API_KEY
          - path: SQS_WORKER_URL
            objectAlias: SQS_WORKER_URL
  secretObjects:
    - secretName: {{ .Values.app.secretName }}
      type: Opaque
      data:
        - objectName: DATABASE_URL
          key: DATABASE_URL
        - objectName: JWT_SECRET
          key: JWT_SECRET
        - objectName: GCS_PROJECT_ID
          key: GCS_PROJECT_ID
        - objectName: GCS_PUBLIC_BUCKET_NAME
          key: GCS_PUBLIC_BUCKET_NAME
        - objectName: GCS_PRIVATE_BUCKET_NAME
          key: GCS_PRIVATE_BUCKET_NAME
        - objectName: GCS_CREDENTIALS
          key: GCS_CREDENTIALS
        - objectName: DATADOG_API_KEY
          key: DATADOG_API_KEY
        - objectName: SQS_WORKER_URL
          key: SQS_WORKER_URL
