apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.app.secretName }}
  namespace: {{ .Values.app.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.app.secretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: kunlatek/app
